kind: ConfigMap
metadata:
  name: burrow-config
  namespace: monitoring-test
apiVersion: v1
data:
  burrow.toml: |-
    [zookeeper]
    servers=[ "zookeeper-v2-headless.zookeeper-cluster:2181" ]
    timeout=6
    root-path="/burrow"

    [cluster.local]
    class-name="kafka"
    servers=[ "kafka-v2-headless.kafka-cluster:9092" ]
    topic-refresh=60
    offset-refresh=30

    [consumer.local]
    class-name="kafka"
    cluster="local"
    servers=[ "kafka-v2-headless.kafka-cluster:9092" ]
    group-blacklist=""
    group-whitelist=""

    [consumer.local_zk]
    class-name="kafka_zk"
    cluster="local"
    servers=[ "zookeeper-v2-headless.zookeeper-cluster:2181" ]
    zookeeper-path="/local"
    zookeeper-timeout=30
    group-blacklist=""
    group-whitelist=""

    [httpserver.default]
    address=":8000"
